build: fix configure failure in gcc-14
```
$ ./configure
[    5s] Checking for curses header file... no
[    5s] !! Can not find curses/tinfo library. The curses/tinfo library is required to compile libt3key.
$ cat config.log
…
.config.c:8:13: error: implicit declaration of function "setupterm";
did you mean ‘set_term’? [-Wimplicit-function-declaration]
```